//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentPlant.DataCore.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentPlant.DataCore.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source name is required..
        /// </summary>
        internal static string Error_DataSourceNameIsRequired {
            get {
                return ResourceManager.GetString("Error_DataSourceNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-good status code was returned: {0} {1} {2}/{3}.
        /// </summary>
        internal static string Error_DefaultHttpErrorMessage {
            get {
                return ResourceManager.GetString("Error_DefaultHttpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event sink name is required..
        /// </summary>
        internal static string Error_EventSinkNameIsRequired {
            get {
                return ResourceManager.GetString("Error_EventSinkNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event source name is required..
        /// </summary>
        internal static string Error_EventSourceNameIsRequired {
            get {
                return ResourceManager.GetString("Error_EventSourceNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A base Data Core URL must be provided..
        /// </summary>
        internal static string Error_HttpClientRequiresBaseUrl {
            get {
                return ResourceManager.GetString("Error_HttpClientRequiresBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a data source name..
        /// </summary>
        internal static string Error_InvalidDataSourceName {
            get {
                return ResourceManager.GetString("Error_InvalidDataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid TimeSpan literal or sample interval (&quot;1d&quot;, &quot;30m&quot;, &quot;15s&quot;) must be specified..
        /// </summary>
        internal static string Error_InvalidSampleInterval {
            get {
                return ResourceManager.GetString("Error_InvalidSampleInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid absolute or relative sample time must be specified..
        /// </summary>
        internal static string Error_InvalidTimeStamp {
            get {
                return ResourceManager.GetString("Error_InvalidTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more role names are required..
        /// </summary>
        internal static string Error_OneOrMoreRoleNamesRequired {
            get {
                return ResourceManager.GetString("Error_OneOrMoreRoleNamesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positive sample interval is required..
        /// </summary>
        internal static string Error_PositiveSampleIntervalIsRequired {
            get {
                return ResourceManager.GetString("Error_PositiveSampleIntervalIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A script engine ID is required..
        /// </summary>
        internal static string Error_ScriptEngineIdIsRequired {
            get {
                return ResourceManager.GetString("Error_ScriptEngineIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated data function list cannot contain any of the following functions: {0}.
        /// </summary>
        internal static string Error_Scripting_AggregatedFunctionListCanContainOnlyAggregateFunctions {
            get {
                return ResourceManager.GetString("Error_Scripting_AggregatedFunctionListCanContainOnlyAggregateFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated data function list cannot be empty..
        /// </summary>
        internal static string Error_Scripting_AggregatedFunctionListCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_Scripting_AggregatedFunctionListCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated data function list cannot contain null or white space values..
        /// </summary>
        internal static string Error_Scripting_AggregatedFunctionListCannotContainEmptyValues {
            get {
                return ResourceManager.GetString("Error_Scripting_AggregatedFunctionListCannotContainEmptyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital state names cannot be longer than {0} characters: &quot;{1}&quot;.
        /// </summary>
        internal static string Error_Scripting_DigitalStateNameIsTooLong {
            get {
                return ResourceManager.GetString("Error_Scripting_DigitalStateNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event definition names cannot be longer than {0} characters: &quot;{1}&quot;.
        /// </summary>
        internal static string Error_Scripting_EventDefinitionNameIsTooLong {
            get {
                return ResourceManager.GetString("Error_Scripting_EventDefinitionNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event definition is required: &quot;{0}&quot;.
        /// </summary>
        internal static string Error_Scripting_EventDefinitionValueCannotBeNull {
            get {
                return ResourceManager.GetString("Error_Scripting_EventDefinitionValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching for script tags..
        /// </summary>
        internal static string Error_Scripting_FindScriptTagsAsync_HttpError {
            get {
                return ResourceManager.GetString("Error_Scripting_FindScriptTagsAsync_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while requesting a script template..
        /// </summary>
        internal static string Error_Scripting_GetExtendedScriptTemplateAsync_HttpError {
            get {
                return ResourceManager.GetString("Error_Scripting_GetExtendedScriptTemplateAsync_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while requesting script engines..
        /// </summary>
        internal static string Error_Scripting_GetScriptEnginesAsync_HttpError {
            get {
                return ResourceManager.GetString("Error_Scripting_GetScriptEnginesAsync_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving a script tag..
        /// </summary>
        internal static string Error_Scripting_GetScriptTagAsync_HttpError {
            get {
                return ResourceManager.GetString("Error_Scripting_GetScriptTagAsync_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving script tags..
        /// </summary>
        internal static string Error_Scripting_GetScriptTagsAsync_HttpError {
            get {
                return ResourceManager.GetString("Error_Scripting_GetScriptTagsAsync_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot request more than {0} tags..
        /// </summary>
        internal static string Error_Scripting_GetScriptTagsAsync_TagCountIsTooLarge {
            get {
                return ResourceManager.GetString("Error_Scripting_GetScriptTagsAsync_TagCountIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while requesting script templates..
        /// </summary>
        internal static string Error_Scripting_GetScriptTemplatesAsync_HttpError {
            get {
                return ResourceManager.GetString("Error_Scripting_GetScriptTemplatesAsync_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data block size must be greater than zero..
        /// </summary>
        internal static string Error_Scripting_InputDataBlockSizeMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Error_Scripting_InputDataBlockSizeMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data sample interval must be greater than zero..
        /// </summary>
        internal static string Error_Scripting_InputDataSampleIntervalMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Error_Scripting_InputDataSampleIntervalMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a script engine ID..
        /// </summary>
        internal static string Error_Scripting_InvalidEngineId {
            get {
                return ResourceManager.GetString("Error_Scripting_InvalidEngineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a script template name..
        /// </summary>
        internal static string Error_Scripting_InvalidTemplateName {
            get {
                return ResourceManager.GetString("Error_Scripting_InvalidTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a valid time span..
        /// </summary>
        internal static string Error_Scripting_InvalidTimeSpan {
            get {
                return ResourceManager.GetString("Error_Scripting_InvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a schedule trigger, a schedule must be defined..
        /// </summary>
        internal static string Error_Scripting_ScheduleIsRequired {
            get {
                return ResourceManager.GetString("Error_Scripting_ScheduleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag reference names must start with a letter or an underscore, and can only consist of letters, numbers, or underscores: &quot;{0}&quot;.
        /// </summary>
        internal static string Error_Scripting_TagReferenceNameIsInvalid {
            get {
                return ResourceManager.GetString("Error_Scripting_TagReferenceNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag reference names cannot be longer than {0} characters: &quot;{1}&quot;.
        /// </summary>
        internal static string Error_Scripting_TagReferenceNameIsTooLong {
            get {
                return ResourceManager.GetString("Error_Scripting_TagReferenceNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag reference definition is required: &quot;{0}&quot;.
        /// </summary>
        internal static string Error_Scripting_TagReferenceValueCannotBeNull {
            get {
                return ResourceManager.GetString("Error_Scripting_TagReferenceValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a template parameter name is {0} characters: &quot;{1}&quot;.
        /// </summary>
        internal static string Error_Scripting_TemplateParameterNameIsTooLong {
            get {
                return ResourceManager.GetString("Error_Scripting_TemplateParameterNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of digital states is {0}..
        /// </summary>
        internal static string Error_Scripting_TooManyDigitalStates {
            get {
                return ResourceManager.GetString("Error_Scripting_TooManyDigitalStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of event definitions is {0}..
        /// </summary>
        internal static string Error_Scripting_TooManyEventDefinitions {
            get {
                return ResourceManager.GetString("Error_Scripting_TooManyEventDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of tag references is {0}..
        /// </summary>
        internal static string Error_Scripting_TooManyTagReferences {
            get {
                return ResourceManager.GetString("Error_Scripting_TooManyTagReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time cannot be greater than end time..
        /// </summary>
        internal static string Error_StartTimeCannotBeGreaterThanEndTime {
            get {
                return ResourceManager.GetString("Error_StartTimeCannotBeGreaterThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag map or list cannot contain null items..
        /// </summary>
        internal static string Error_TagMapOrListCannotContainNullItems {
            get {
                return ResourceManager.GetString("Error_TagMapOrListCannotContainNullItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag name is required..
        /// </summary>
        internal static string Error_TagNameIsRequired {
            get {
                return ResourceManager.GetString("Error_TagNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template name is required..
        /// </summary>
        internal static string Error_TemplateNameIsRequired {
            get {
                return ResourceManager.GetString("Error_TemplateNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of values to write cannot contain null items..
        /// </summary>
        internal static string Error_WriteValuesCannotContainNullItems {
            get {
                return ResourceManager.GetString("Error_WriteValuesCannotContainNullItems", resourceCulture);
            }
        }
    }
}
