//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentPlant.IndustrialAppStore.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentPlant.IndustrialAppStore.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Funds.
        /// </summary>
        internal static string DebitUserResponse_Message_InsufficientFunds {
            get {
                return ResourceManager.GetString("DebitUserResponse_Message_InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Successful.
        /// </summary>
        internal static string DebitUserResponse_Message_Success {
            get {
                return ResourceManager.GetString("DebitUserResponse_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Failed.
        /// </summary>
        internal static string DebitUserResponse_Message_TransactionFailed {
            get {
                return ResourceManager.GetString("DebitUserResponse_Message_TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Response Code: {0}.
        /// </summary>
        internal static string DebitUserResponse_Message_UnexpectedResponseCode {
            get {
                return ResourceManager.GetString("DebitUserResponse_Message_UnexpectedResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A base Industrial App Store API URL must be provided..
        /// </summary>
        internal static string Error_BaseUrlIsRequired {
            get {
                return ResourceManager.GetString("Error_BaseUrlIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Failed: {0}.
        /// </summary>
        internal static string RefundUserResponse_Message_Failed {
            get {
                return ResourceManager.GetString("RefundUserResponse_Message_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Successful.
        /// </summary>
        internal static string RefundUserResponse_Message_Success {
            get {
                return ResourceManager.GetString("RefundUserResponse_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Response Code: {0}.
        /// </summary>
        internal static string RefundUserResponse_Message_UnexpectedResponseCode {
            get {
                return ResourceManager.GetString("RefundUserResponse_Message_UnexpectedResponseCode", resourceCulture);
            }
        }
    }
}
